sudo: required
dist: bionic
language: chsarp
mono: none
dotnet:5.0
services: docker
before_install:
  - cd RestWithASPNETUdemy
  - echo "We are in the right folder!"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag rest-with-asp-net-udemy-db: latest $DOCKER_USERNAME/rest-with-udemy-aps-net-udemy-db:latest;
    docker tag rest-with-asp-net-udemy: latest $DOCKER_USERNAME/rest-with-udemy-aps-net-udemy:latest;
    docker push $DOCKER_USERNAME/rest-with-udemy-aps-net-udemy;
    docker push $DOCKER_USERNAME/rest-with-udemy-aps-net-udemy-db;
  on:
    branch: main
notifications:
  email: false
